### PR TITLE
MNT: Add noarch: python

### LINKED ISSUE #5: @conda-forge-admin, please make noarch: python
It looks to me like this recipe can be made `noarch: python`, which would make it installable on Python 3.7.

cc @gonzalocasas

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've made the recipe `noarch: python` as instructed in #5.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes #5

### CODE REVIEW

**Comment by dougalsutherland** [comment]
Error is
```
[noarch_python] Error: Binary library or executable found: lib/python2.7/site-packages/compas/numerical/fd/__fd_cpp/fd.so
```

But, unusually, compas installation didn't actually compile this `.so`; it's [distributed in the source](https://github.com/compas-dev/compas/tree/master/src/compas/numerical/fd/__fd_cpp) (along with a `.dll`). Dunno how that actually works, but although it shouldn't in theory stop this from being `noarch: python`, conda-build [has a non-overridable check for it](https://github.com/conda/conda-build/blob/19f5d7847ee8a4c5b979680595103fa6cc21e4b1/conda_build/noarch_python.py#L60-L66). Opening a conda-build issue about it.

In the meantime, I think `compas` isn't rerendering with a 3.7 build because conda-forge doesn't yet have a `numba` package for 3.7. That should hopefully be resolved before too long; the only missing dependency is `llvmlite`, which is [in process](https://github.com/conda-forge/llvmlite-feedstock/pull/11).

**Comment by gonzalocasas** [comment]
@dougalsutherland thanks a lot for this! I created [an issue on compas](https://github.com/compas-dev/compas/issues/191) to remove the compiled files from the repo.

Regarding `noarch`, I was [asked originally](https://github.com/conda-forge/staged-recipes/pull/6538#discussion_r211804567) if we could make it `noarch`, and I thought it wouldn't work because chances are we will add more platform-specific stuff as we move forward. However, until that happens, perhaps it is best to switch to `noarch` to save resources, and only switch back once we effectively need it.

In the meantime, do you think we should close this PR until `numba` is on 3.7? Or we keep it around until then?

**Comment by dougalsutherland** [comment]
> I created an issue on compas to remove the compiled files from the repo.

I have no idea how your precompiled `.so`s would work on different systems (e.g. Mac). But yeah, if they get put in the build script, as one would normally expect, then this package won't be able to be noarch (as you expected). Note that this might cause a problem e.g. for Windows users who install via `pip` unless you also start publishing binary wheels.

This PR is specifically about noarch, so if you don't think it makes sense to make it noarch, then sure, close it. After a numba 3.7 build is available, you can get a compas 3.7 one by just asking the bot to rerender.

**Comment by gonzalocasas** [comment]
I'll close this for the time being.

**Comment by gonzalocasas** [comment]
I'll close this for the time being.

**Pull request closed without merging**
