### PR TITLE
Add typing extensions for py36 and py37

### PR DESCRIPTION
**Pull request by brgcode**

### CODE REVIEW

**Comment by gonzalocasas** [comment]
shouldn't this PR also do all the version bumping the closed one did?

**Comment by brgcode** [comment]
i needed to update the code and release a patch as well so i assumed the recipe needed to be updated separately

**Comment by gonzalocasas** [comment]
ah nah, we can do it in this pr.. it's just setting version to 1.8.1 and hash is `74f79b7c64e920122f6ac18a251f7ad93681a2406c4633c1c65499905991bc40` (according to pip)

**Comment by gonzalocasas** [comment]
@conda-forge-admin please rerender

**Pull request merged**
