### PR TITLE
version 0.4.0 build 0 dependency cython planarity

### PR DESCRIPTION
**Pull request by brgcode**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gonzalocasas** [comment]
Mmmm... we have two problems:
 - On Linux with Python 2.7, Circle-CI is complaining that `ImportError: Failed to import any qt binding`
 - The recipe on conda for `planarity` is not available for Windows at all (it's explicitly [skipped](https://github.com/conda-forge/planarity-feedstock/blob/master/recipe/meta.yaml#L19)), only OSX and Linux, so all Windows builds in AppVeyor are failing.

I'm not sure how to resolve the later

**Comment by brgcode** [comment]
okay, perhaps it is not necessary to include it and can be listed as an optional dependency. i will make a pr :)

**Comment by brgcode** [comment]
read somewhere that `qt` error is due to `matplotlib` and that it can be solved by requiring `matplotlib>=3.0`...

**Comment by gonzalocasas** [comment]
```
import: 'compas'
import: 'compas_blender'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/test_tmp/run_test.py", line 5, in <module>
    import compas_blender
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/compas_blender/__init__.py", line 23, in <module>
    from .utilities import *
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/compas_blender/utilities/__init__.py", line 131, in <module>
    from .drawing import *
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/compas_blender/utilities/drawing.py", line 9, in <module>
    from compas.geometry import centroid_points
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/compas/geometry/__init__.py", line 410, in <module>
    from .bestfit import *
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/compas/geometry/bestfit/__init__.py", line 7, in <module>
    from .bestfit_numpy import *
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/compas/geometry/bestfit/bestfit_numpy.py", line 11, in <module>
    from compas.numerical import pca_numpy
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/compas/numerical/__init__.py", line 116, in <module>
    from .devo import *
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/compas/numerical/devo/__init__.py", line 6, in <module>
    from .devo_numpy import *
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/compas/numerical/devo/devo_numpy.py", line 31, in <module>
    compas.raise_if_not_ironpython()
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/compas/numerical/devo/devo_numpy.py", line 26, in <module>
    from matplotlib import pyplot as plt
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/home/conda/feedstock_root/build_artifacts/compas_1547514383523/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 158, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```

**Comment by brgcode** [comment]
so, also due to `matplotlib`, no?

**Comment by brgcode** [comment]
https://stackoverflow.com/questions/52346254/importerror-failed-to-import-any-qt-binding-python-tensorflow

**Pull request merged**
