### PR TITLE
adding py3.5

### PR DESCRIPTION
**Pull request by brgcode**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by brgcode** [comment]
<code>@<space/>conda-forge-admin, please rerender</code>

**Comment by gonzalocasas** [comment]
@brgcode should we close this or merge it?

**Comment by brgcode** [comment]
i guess we can merge it but it is in fact not really necessary anymore since we dropped support for anything but blender 2.8.

or should we also support some of the older versions?

**Comment by gonzalocasas** [comment]
I would vote for closing, supporting older blender is unlikely ;)

**Comment by brgcode** [comment]
will change the requirements back to non-py35 compatible then

**Pull request closed without merging**
